"""Versioned mixed-I/O geometry and a deterministic CPU reference model.

This module is the Phase 9B contract shared by artifact generation, receipt
validation and the native GIDS/BaM path.  All addresses are byte based;
``storage_row`` remains the public feature index used by the artifact and
sampler.
"""

from __future__ import annotations

# Locate DiGiT independently of the checkout directory and working directory.
from pathlib import Path as _DigitPath
import sys as _digit_sys
_digit_root = next((p for p in _DigitPath(__file__).resolve().parents
                    if (p / ".digit-root").is_file()), None)
if _digit_root is None:
    raise RuntimeError("Cannot locate the DiGiT project root")
if str(_digit_root) not in _digit_sys.path:
    _digit_sys.path.insert(0, str(_digit_root))
import digit_paths as _digit_paths

import hashlib
import json
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

import numpy as np


GEOMETRY_SCHEMA_NAME = "digit-io-geometry"
GEOMETRY_SCHEMA_VERSION = 1
DEFAULT_MIN_TRANSFER_BYTES = 4096
DEFAULT_TARGET_REQUEST_BYTES = 8192
DEFAULT_VALIDITY_MASK_BITS = 64


class GeometryValidationError(ValueError):
    """Raised when an I/O geometry cannot be represented safely."""


def _integer(value: Any, name: str, *, minimum: int = 0) -> int:
    if isinstance(value, bool) or not isinstance(value, (int, np.integer)):
        raise GeometryValidationError("{} must be an integer".format(name))
    result = int(value)
    if result < minimum:
        raise GeometryValidationError(
            "{} must be at least {}".format(name, minimum)
        )
    return result


def _power_of_two(value: int) -> bool:
    return value > 0 and value & (value - 1) == 0


def _ceil_div(value: int, divisor: int) -> int:
    return (value + divisor - 1) // divisor


def _align_up(value: int, alignment: int) -> int:
    return _ceil_div(value, alignment) * alignment


def _popcount(value: int) -> int:
    return bin(value).count("1")


def select_group_size(feature_row_bytes: int, target_request_bytes: int) -> int:
    """Choose the number of complete feature rows in a target group request.

    Auto selection is deliberately exact: a target that is not an integer
    number of rows is rejected rather than silently changing the requested
    transfer size. Explicit group-size sensitivity runs use ``IOGeometry.create``
    with ``group_size`` set directly and may therefore contain padding.
    """

    row = _integer(feature_row_bytes, "feature_row_bytes", minimum=1)
    target = _integer(target_request_bytes, "target_request_bytes", minimum=1)
    if target < row:
        raise GeometryValidationError(
            "target_request_bytes cannot be smaller than one feature row"
        )
    if target % row:
        raise GeometryValidationError(
            "target_request_bytes must contain an integer number of feature rows"
        )
    return target // row


@dataclass(frozen=True)
class IOCommand:
    """One aligned device transfer generated by the reference planner."""

    slot_index: int
    first_subrow: int
    subrow_count: int
    device_offset_bytes: int
    length_bytes: int


@dataclass(frozen=True)
class RequestPlan:
    """Address and validity-mask expansion for one feature-row request."""

    storage_row: int
    is_group: bool
    slot_index: int
    row_in_slot: int
    row_offset_bytes: int
    requested_mask: int
    valid_mask_before: int
    hit_mask: int
    missing_mask: int
    commands: Tuple[IOCommand, ...]


@dataclass(frozen=True)
class IOGeometry:
    """Validated v1 contract shared by artifacts, CUDA and SSD receipts."""

    feature_row_bytes: int
    minimum_transfer_bytes: int
    transfer_alignment_bytes: int
    group_size: int
    group_bytes: int
    raw_transfer_bytes: int
    group_transfer_bytes: int
    cache_slot_bytes: int
    subrow_bytes: int
    subrow_count: int
    rows_per_slot: int
    padding_bytes: int
    padding_rows: int
    payload_offset_bytes: int
    target_request_bytes: int
    group_size_selection: str
    validity_mask_bits: int = DEFAULT_VALIDITY_MASK_BITS

    @classmethod
    def create(
        cls,
        *,
        feature_row_bytes: int,
        group_size: Optional[int] = None,
        minimum_transfer_bytes: int = DEFAULT_MIN_TRANSFER_BYTES,
        transfer_alignment_bytes: Optional[int] = None,
        target_request_bytes: int = DEFAULT_TARGET_REQUEST_BYTES,
        payload_offset_bytes: int = 0,
        validity_mask_bits: int = DEFAULT_VALIDITY_MASK_BITS,
    ) -> "IOGeometry":
        row = _integer(feature_row_bytes, "feature_row_bytes", minimum=1)
        minimum = _integer(
            minimum_transfer_bytes, "minimum_transfer_bytes", minimum=1
        )
        alignment = minimum if transfer_alignment_bytes is None else _integer(
            transfer_alignment_bytes, "transfer_alignment_bytes", minimum=1
        )
        target = _integer(target_request_bytes, "target_request_bytes", minimum=1)
        payload_offset = _integer(
            payload_offset_bytes, "payload_offset_bytes", minimum=0
        )
        mask_bits = _integer(validity_mask_bits, "validity_mask_bits", minimum=1)

        if not _power_of_two(minimum) or not _power_of_two(alignment):
            raise GeometryValidationError(
                "minimum transfer and transfer alignment must be powers of two"
            )
        if minimum % alignment:
            raise GeometryValidationError(
                "minimum_transfer_bytes must be a multiple of transfer_alignment_bytes"
            )
        if payload_offset % minimum:
            raise GeometryValidationError(
                "payload_offset_bytes must be minimum-transfer aligned"
            )
        if minimum % row and row % minimum:
            raise GeometryValidationError(
                "feature row and minimum transfer must divide one another"
            )

        if group_size is None:
            selected_group_size = select_group_size(row, target)
            selection = "auto"
        else:
            selected_group_size = _integer(group_size, "group_size", minimum=1)
            selection = "explicit"

        group_bytes = selected_group_size * row
        raw_transfer = _align_up(row, minimum)
        group_transfer = _align_up(group_bytes, minimum)
        slot_bytes = group_transfer
        if slot_bytes % row:
            raise GeometryValidationError(
                "cache slot cannot be represented as complete feature rows"
            )
        subrows = slot_bytes // minimum
        if subrows > mask_bits:
            raise GeometryValidationError(
                "cache slot requires {} validity bits but only {} are available".format(
                    subrows, mask_bits
                )
            )
        padding = slot_bytes - group_bytes
        if padding % row:
            raise GeometryValidationError(
                "group padding cannot be represented as complete storage rows"
            )

        geometry = cls(
            feature_row_bytes=row,
            minimum_transfer_bytes=minimum,
            transfer_alignment_bytes=alignment,
            group_size=selected_group_size,
            group_bytes=group_bytes,
            raw_transfer_bytes=raw_transfer,
            group_transfer_bytes=group_transfer,
            cache_slot_bytes=slot_bytes,
            subrow_bytes=minimum,
            subrow_count=subrows,
            rows_per_slot=slot_bytes // row,
            padding_bytes=padding,
            padding_rows=padding // row,
            payload_offset_bytes=payload_offset,
            target_request_bytes=target,
            group_size_selection=selection,
            validity_mask_bits=mask_bits,
        )
        geometry.validate()
        return geometry

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "IOGeometry":
        """Load and re-derive a serialized contract, rejecting stale fields."""

        required_top = {"schema_name", "schema_version", "feature", "nvme", "group", "cache", "layout"}
        if set(value) != required_top:
            raise GeometryValidationError(
                "geometry contract keys differ: expected {}".format(
                    sorted(required_top)
                )
            )
        if value["schema_name"] != GEOMETRY_SCHEMA_NAME:
            raise GeometryValidationError("unsupported geometry schema_name")
        if value["schema_version"] != GEOMETRY_SCHEMA_VERSION:
            raise GeometryValidationError("unsupported geometry schema_version")

        feature = value["feature"]
        nvme = value["nvme"]
        group = value["group"]
        cache = value["cache"]
        layout = value["layout"]
        expected_keys = {
            "feature": {"row_bytes"},
            "nvme": {"minimum_transfer_bytes", "transfer_alignment_bytes"},
            "group": {
                "size", "logical_bytes", "transfer_bytes", "target_request_bytes", "selection"
            },
            "cache": {
                "slot_bytes", "subrow_bytes", "subrow_count", "validity_mask_bits", "full_valid_mask"
            },
            "layout": {
                "rows_per_slot", "padding_bytes", "padding_rows", "payload_offset_bytes", "raw_transfer_bytes"
            },
        }
        for name, mapping in (
            ("feature", feature), ("nvme", nvme), ("group", group),
            ("cache", cache), ("layout", layout),
        ):
            if not isinstance(mapping, Mapping) or set(mapping) != expected_keys[name]:
                raise GeometryValidationError("invalid geometry {} object".format(name))

        geometry = cls.create(
            feature_row_bytes=feature["row_bytes"],
            group_size=group["size"],
            minimum_transfer_bytes=nvme["minimum_transfer_bytes"],
            transfer_alignment_bytes=nvme["transfer_alignment_bytes"],
            target_request_bytes=group["target_request_bytes"],
            payload_offset_bytes=layout["payload_offset_bytes"],
            validity_mask_bits=cache["validity_mask_bits"],
        )
        if group["selection"] == "auto":
            if select_group_size(
                geometry.feature_row_bytes, geometry.target_request_bytes
            ) != geometry.group_size:
                raise GeometryValidationError("serialized auto group size is inconsistent")
            geometry = cls(**{**geometry.__dict__, "group_size_selection": "auto"})
        elif group["selection"] != "explicit":
            raise GeometryValidationError("group.selection must be auto or explicit")
        if geometry.to_dict() != dict(value):
            raise GeometryValidationError("serialized geometry contains inconsistent derived fields")
        return geometry

    @classmethod
    def from_artifact_manifest(
        cls,
        manifest: Mapping[str, Any],
        *,
        minimum_transfer_bytes: int = DEFAULT_MIN_TRANSFER_BYTES,
        transfer_alignment_bytes: Optional[int] = None,
        target_request_bytes: int = DEFAULT_TARGET_REQUEST_BYTES,
        payload_offset_bytes: int = 0,
    ) -> "IOGeometry":
        """Derive a contract from a legacy v1 artifact and verify its slot size."""

        try:
            row_bytes = manifest["feature"]["row_bytes"]
            group_size = manifest["grouping"]["group_size"]
            artifact_page_size = int(manifest["io"]["page_size"])
        except (KeyError, TypeError, ValueError) as error:
            raise GeometryValidationError("artifact has no valid I/O geometry") from error
        geometry = cls.create(
            feature_row_bytes=row_bytes,
            group_size=group_size,
            minimum_transfer_bytes=minimum_transfer_bytes,
            transfer_alignment_bytes=transfer_alignment_bytes,
            target_request_bytes=target_request_bytes,
            payload_offset_bytes=payload_offset_bytes,
        )
        if geometry.cache_slot_bytes != artifact_page_size:
            raise GeometryValidationError(
                "artifact page_size {} does not match derived cache slot {}".format(
                    artifact_page_size, geometry.cache_slot_bytes
                )
            )
        return geometry

    @property
    def full_valid_mask(self) -> int:
        return (1 << self.subrow_count) - 1

    def validate(self) -> None:
        """Re-derive every dependent value to detect an invalid direct constructor."""

        for name in (
            "feature_row_bytes", "minimum_transfer_bytes", "transfer_alignment_bytes",
            "group_size", "group_bytes", "raw_transfer_bytes", "group_transfer_bytes",
            "cache_slot_bytes", "subrow_bytes", "subrow_count", "rows_per_slot",
            "padding_bytes", "padding_rows", "target_request_bytes", "validity_mask_bits",
        ):
            _integer(getattr(self, name), name, minimum=1 if name not in ("padding_bytes", "padding_rows") else 0)
        _integer(self.payload_offset_bytes, "payload_offset_bytes", minimum=0)
        if self.group_size_selection not in ("auto", "explicit"):
            raise GeometryValidationError("group_size_selection must be auto or explicit")
        if not _power_of_two(self.minimum_transfer_bytes) or not _power_of_two(
            self.transfer_alignment_bytes
        ):
            raise GeometryValidationError(
                "minimum transfer and transfer alignment must be powers of two"
            )
        if self.minimum_transfer_bytes % self.transfer_alignment_bytes:
            raise GeometryValidationError(
                "minimum transfer must be a multiple of transfer alignment"
            )
        if (
            self.minimum_transfer_bytes % self.feature_row_bytes
            and self.feature_row_bytes % self.minimum_transfer_bytes
        ):
            raise GeometryValidationError(
                "feature row and minimum transfer must divide one another"
            )
        if self.group_bytes != self.group_size * self.feature_row_bytes:
            raise GeometryValidationError("group_bytes is inconsistent")
        if self.raw_transfer_bytes != _align_up(
            self.feature_row_bytes, self.minimum_transfer_bytes
        ):
            raise GeometryValidationError("raw_transfer_bytes is inconsistent")
        if self.group_transfer_bytes != _align_up(
            self.group_bytes, self.minimum_transfer_bytes
        ):
            raise GeometryValidationError("group_transfer_bytes is inconsistent")
        if self.cache_slot_bytes != self.group_transfer_bytes:
            raise GeometryValidationError("cache_slot_bytes is inconsistent")
        if self.cache_slot_bytes % self.feature_row_bytes:
            raise GeometryValidationError("cache slot does not contain complete rows")
        if self.subrow_bytes != self.minimum_transfer_bytes:
            raise GeometryValidationError("subrow_bytes is inconsistent")
        if self.subrow_count != self.cache_slot_bytes // self.subrow_bytes:
            raise GeometryValidationError("subrow_count is inconsistent")
        if self.rows_per_slot != self.cache_slot_bytes // self.feature_row_bytes:
            raise GeometryValidationError("rows_per_slot is inconsistent")
        if self.padding_bytes != self.cache_slot_bytes - self.group_bytes:
            raise GeometryValidationError("padding_bytes is inconsistent")
        if self.padding_rows != self.padding_bytes // self.feature_row_bytes:
            raise GeometryValidationError("padding_rows is inconsistent")
        if self.subrow_count > self.validity_mask_bits:
            raise GeometryValidationError("validity mask is too narrow")
        if self.payload_offset_bytes % self.minimum_transfer_bytes:
            raise GeometryValidationError("payload offset is not transfer aligned")
        if self.group_size_selection == "auto" and self.group_size != select_group_size(
            self.feature_row_bytes, self.target_request_bytes
        ):
            raise GeometryValidationError("auto group size is inconsistent")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "schema_name": GEOMETRY_SCHEMA_NAME,
            "schema_version": GEOMETRY_SCHEMA_VERSION,
            "feature": {"row_bytes": self.feature_row_bytes},
            "nvme": {
                "minimum_transfer_bytes": self.minimum_transfer_bytes,
                "transfer_alignment_bytes": self.transfer_alignment_bytes,
            },
            "group": {
                "size": self.group_size,
                "logical_bytes": self.group_bytes,
                "transfer_bytes": self.group_transfer_bytes,
                "target_request_bytes": self.target_request_bytes,
                "selection": self.group_size_selection,
            },
            "cache": {
                "slot_bytes": self.cache_slot_bytes,
                "subrow_bytes": self.subrow_bytes,
                "subrow_count": self.subrow_count,
                "validity_mask_bits": self.validity_mask_bits,
                "full_valid_mask": self.full_valid_mask,
            },
            "layout": {
                "rows_per_slot": self.rows_per_slot,
                "padding_bytes": self.padding_bytes,
                "padding_rows": self.padding_rows,
                "payload_offset_bytes": self.payload_offset_bytes,
                "raw_transfer_bytes": self.raw_transfer_bytes,
            },
        }

    def semantic_sha256(self) -> str:
        encoded = json.dumps(
            self.to_dict(), sort_keys=True, separators=(",", ":")
        ).encode("utf-8")
        return hashlib.sha256(encoded).hexdigest()

    def to_native_mapping(self) -> Dict[str, Any]:
        """Return the flat, hash-bound subset consumed by the GIDS ABI."""

        return {
            "feature_row_bytes": self.feature_row_bytes,
            "minimum_transfer_bytes": self.minimum_transfer_bytes,
            "group_size": self.group_size,
            "subrow_count": self.subrow_count,
            "full_valid_mask": self.full_valid_mask,
            "cache_slot_bytes": self.cache_slot_bytes,
            "sha256": self.semantic_sha256(),
        }

    def with_payload_offset(self, payload_offset_bytes: int) -> "IOGeometry":
        geometry = IOGeometry.create(
            feature_row_bytes=self.feature_row_bytes,
            group_size=self.group_size,
            minimum_transfer_bytes=self.minimum_transfer_bytes,
            transfer_alignment_bytes=self.transfer_alignment_bytes,
            target_request_bytes=self.target_request_bytes,
            payload_offset_bytes=payload_offset_bytes,
            validity_mask_bits=self.validity_mask_bits,
        )
        if self.group_size_selection == "auto":
            geometry = IOGeometry(
                **{**geometry.__dict__, "group_size_selection": "auto"}
            )
        return geometry

    def save(self, path: Path) -> str:
        target = Path(path)
        if target.exists():
            raise FileExistsError("geometry contract already exists: {}".format(target))
        target.parent.mkdir(parents=True, exist_ok=True)
        temporary = target.with_suffix(target.suffix + ".tmp")
        temporary.write_text(
            json.dumps(self.to_dict(), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        temporary.replace(target)
        return self.semantic_sha256()

    @classmethod
    def load(cls, path: Path) -> "IOGeometry":
        return cls.from_dict(_digit_paths.json_loads(Path(path).read_text(encoding="utf-8")))

    def row_location(self, storage_row: int) -> Tuple[int, int, int]:
        row = _integer(storage_row, "storage_row", minimum=0)
        byte_offset = row * self.feature_row_bytes
        slot = byte_offset // self.cache_slot_bytes
        offset_in_slot = byte_offset % self.cache_slot_bytes
        return slot, offset_in_slot // self.feature_row_bytes, offset_in_slot

    def requested_mask(self, storage_row: int, is_group: bool) -> int:
        _, row_in_slot, byte_in_slot = self.row_location(storage_row)
        if is_group:
            if row_in_slot >= self.group_size:
                raise GeometryValidationError(
                    "group request points into slot padding rather than a group member"
                )
            return self.full_valid_mask
        first = byte_in_slot // self.subrow_bytes
        last = (byte_in_slot + self.feature_row_bytes - 1) // self.subrow_bytes
        return ((1 << (last - first + 1)) - 1) << first

    def plan_request(
        self, storage_row: int, is_group: bool, valid_mask: int = 0
    ) -> RequestPlan:
        valid = _integer(valid_mask, "valid_mask", minimum=0)
        if valid & ~self.full_valid_mask:
            raise GeometryValidationError("valid_mask contains an out-of-range subrow")
        slot, row_in_slot, row_offset = self.row_location(storage_row)
        requested = self.requested_mask(storage_row, is_group)
        hit = requested & valid
        missing = requested & ~valid
        commands: List[IOCommand] = []
        # The native path has a prebuilt PRP for each independently fillable
        # minimum-transfer subrow.  A fresh full-group fill can use the cache
        # slot's existing full-page PRP list; every other miss is deliberately
        # issued as one command per subrow.  Keep the CPU oracle identical to
        # that policy instead of coalescing adjacent partial-mask bits.
        if is_group and missing == self.full_valid_mask:
            command_ranges = ((0, self.subrow_count),)
        else:
            command_ranges = tuple(
                (position, 1)
                for position in range(self.subrow_count)
                if missing & (1 << position)
            )
        for start, count in command_ranges:
            device_offset = (
                self.payload_offset_bytes
                + slot * self.cache_slot_bytes
                + start * self.subrow_bytes
            )
            length = count * self.subrow_bytes
            if device_offset % self.transfer_alignment_bytes:
                raise GeometryValidationError("planned command offset is not aligned")
            commands.append(
                IOCommand(slot, start, count, device_offset, length)
            )
        return RequestPlan(
            storage_row=int(storage_row),
            is_group=bool(is_group),
            slot_index=slot,
            row_in_slot=row_in_slot,
            row_offset_bytes=row_offset,
            requested_mask=requested,
            valid_mask_before=valid,
            hit_mask=hit,
            missing_mask=missing,
            commands=tuple(commands),
        )


@dataclass
class _CacheEntry:
    data: bytearray
    valid_mask: int = 0


class ReferenceMixedIOCache:
    """Deterministic FIFO cache implementing the generalized CPU semantics."""

    def __init__(
        self,
        geometry: IOGeometry,
        payload: Any,
        *,
        capacity_slots: int,
    ) -> None:
        geometry.validate()
        self.geometry = geometry
        self.capacity_slots = _integer(
            capacity_slots, "capacity_slots", minimum=1
        )
        if isinstance(payload, np.ndarray):
            if payload.ndim != 2 or not payload.flags.c_contiguous:
                raise GeometryValidationError("payload array must be contiguous and 2-D")
            if int(payload.strides[0]) != geometry.feature_row_bytes:
                raise GeometryValidationError("payload row width does not match geometry")
            self.dtype = payload.dtype
            self.feature_shape = tuple(payload.shape[1:])
            self._payload = memoryview(payload).cast("B").tobytes()
        else:
            self.dtype = None
            self.feature_shape = None
            self._payload = bytes(payload)
        if len(self._payload) % geometry.cache_slot_bytes:
            raise GeometryValidationError("payload must end on a complete cache slot")
        self._entries: "OrderedDict[int, _CacheEntry]" = OrderedDict()
        self._stats: Dict[str, int] = {}
        self.reset_stats()

    @property
    def num_storage_rows(self) -> int:
        return len(self._payload) // self.geometry.feature_row_bytes

    def reset_stats(self) -> None:
        self._stats = {
            "requests": 0,
            "hits": 0,
            "inserts": 0,
            "partial_fills": 0,
            "evictions": 0,
            "group_rows": 0,
            "raw_rows": 0,
            "group_full_commands": 0,
            "group_partial_commands": 0,
            "raw_commands": 0,
            "group_bytes": 0,
            "raw_bytes": 0,
            "group_subrow_hits": 0,
            "group_subrow_misses": 0,
            "raw_subrow_hits": 0,
            "raw_subrow_misses": 0,
            "physical_bytes": 0,
        }

    def _new_entry(self, slot: int, *, count_stats: bool) -> _CacheEntry:
        if slot in self._entries:
            return self._entries[slot]
        if len(self._entries) >= self.capacity_slots:
            self._entries.popitem(last=False)
            if count_stats:
                self._stats["evictions"] += 1
        entry = _CacheEntry(bytearray(self.geometry.cache_slot_bytes))
        self._entries[slot] = entry
        return entry

    def prime_slot(self, slot_index: int, valid_mask: int) -> None:
        """Install selected source subrows without changing measured counters."""

        slot = _integer(slot_index, "slot_index", minimum=0)
        valid = _integer(valid_mask, "valid_mask", minimum=0)
        if valid & ~self.geometry.full_valid_mask:
            raise GeometryValidationError("valid_mask contains an out-of-range subrow")
        if (slot + 1) * self.geometry.cache_slot_bytes > len(self._payload):
            raise IndexError("slot_index is outside the payload")
        entry = self._new_entry(slot, count_stats=False)
        for subrow in range(self.geometry.subrow_count):
            if valid & (1 << subrow):
                start = slot * self.geometry.cache_slot_bytes + subrow * self.geometry.subrow_bytes
                end = start + self.geometry.subrow_bytes
                local = subrow * self.geometry.subrow_bytes
                entry.data[local : local + self.geometry.subrow_bytes] = self._payload[start:end]
        entry.valid_mask |= valid

    def fetch_row(self, storage_row: int, is_group: bool = False) -> bytes:
        row = _integer(storage_row, "storage_row", minimum=0)
        if row >= self.num_storage_rows:
            raise IndexError("storage_row is outside the payload")
        slot, _, row_offset = self.geometry.row_location(row)
        existing = self._entries.get(slot)
        valid_before = existing.valid_mask if existing is not None else 0
        plan = self.geometry.plan_request(row, bool(is_group), valid_before)

        self._stats["requests"] += 1
        kind = "group" if is_group else "raw"
        self._stats[kind + "_rows"] += 1
        self._stats[kind + "_subrow_hits"] += _popcount(plan.hit_mask)
        self._stats[kind + "_subrow_misses"] += _popcount(plan.missing_mask)

        if not plan.missing_mask:
            self._stats["hits"] += 1
            entry = existing
        else:
            if existing is None:
                entry = self._new_entry(slot, count_stats=True)
                self._stats["inserts"] += 1
            else:
                entry = existing
                self._stats["partial_fills"] += 1
            command_bytes = sum(command.length_bytes for command in plan.commands)
            self._stats[kind + "_bytes"] += command_bytes
            self._stats["physical_bytes"] += command_bytes
            if is_group:
                counter = (
                    "group_full_commands"
                    if valid_before == 0 and plan.missing_mask == self.geometry.full_valid_mask
                    else "group_partial_commands"
                )
                self._stats[counter] += len(plan.commands)
            else:
                self._stats["raw_commands"] += len(plan.commands)
            for command in plan.commands:
                payload_start = (
                    command.slot_index * self.geometry.cache_slot_bytes
                    + command.first_subrow * self.geometry.subrow_bytes
                )
                payload_end = payload_start + command.length_bytes
                local_start = command.first_subrow * self.geometry.subrow_bytes
                entry.data[local_start : local_start + command.length_bytes] = (
                    self._payload[payload_start:payload_end]
                )
            entry.valid_mask |= plan.requested_mask

        assert entry is not None
        start = row_offset
        end = start + self.geometry.feature_row_bytes
        return bytes(entry.data[start:end])

    def fetch_rows(
        self, storage_rows: Sequence[int], group_flags: Sequence[bool]
    ) -> np.ndarray:
        rows = list(storage_rows)
        flags = list(group_flags)
        if len(rows) != len(flags):
            raise GeometryValidationError("storage rows and group flags differ in length")
        raw = b"".join(self.fetch_row(row, flag) for row, flag in zip(rows, flags))
        if self.dtype is None or self.feature_shape is None:
            return np.frombuffer(raw, dtype=np.uint8).reshape(len(rows), -1).copy()
        return np.frombuffer(raw, dtype=self.dtype).reshape(
            (len(rows),) + self.feature_shape
        ).copy()

    def stats(self) -> Dict[str, Any]:
        result: Dict[str, Any] = dict(self._stats)
        result["commands"] = (
            result["group_full_commands"]
            + result["group_partial_commands"]
            + result["raw_commands"]
        )
        result["resident_slots"] = len(self._entries)
        result["capacity_slots"] = self.capacity_slots
        result["average_command_bytes"] = (
            float(result["physical_bytes"]) / result["commands"]
            if result["commands"]
            else 0.0
        )
        result["reconciled"] = bool(
            result["requests"]
            == result["hits"] + result["inserts"] + result["partial_fills"]
            and result["physical_bytes"]
            == result["group_bytes"] + result["raw_bytes"]
            and result["group_subrow_hits"] + result["group_subrow_misses"]
            == result["group_rows"] * self.geometry.subrow_count
            and result["raw_subrow_hits"] + result["raw_subrow_misses"]
            == result["raw_rows"]
            * (self.geometry.raw_transfer_bytes // self.geometry.subrow_bytes)
        )
        return result


def deterministic_feature_payload(geometry: IOGeometry, slots: int = 3) -> np.ndarray:
    """Create bit-distinct float32 rows, including deterministic padding rows."""

    count = _integer(slots, "slots", minimum=1) * geometry.rows_per_slot
    if geometry.feature_row_bytes % 4:
        raise GeometryValidationError("bit-exact float32 probe requires 4-byte rows")
    words = geometry.feature_row_bytes // 4
    base = np.arange(count * words, dtype=np.uint32).reshape(count, words)
    patterns = base ^ np.uint32(0x5A17C9E3)
    return np.ascontiguousarray(patterns.view(np.float32))


def run_bit_exact_geometry_probe(geometry: IOGeometry) -> Dict[str, Any]:
    """Exercise exact data, masks, partial fills, eviction and replica rows."""

    if geometry.subrow_count > 8:
        raise GeometryValidationError(
            "exhaustive partial-mask probe is bounded to eight subrows"
        )
    payload = deterministic_feature_payload(geometry, slots=3)
    digest = hashlib.sha256()

    # Raw miss/hit for a representative row in every transfer subrow.
    rows_per_subrow = geometry.subrow_bytes // geometry.feature_row_bytes
    if rows_per_subrow <= 0:
        rows_per_subrow = 1
    raw_cache = ReferenceMixedIOCache(geometry, payload, capacity_slots=3)
    raw_rows = [
        min(index * rows_per_subrow, geometry.rows_per_slot - 1)
        for index in range(geometry.subrow_count)
    ]
    for row in raw_rows:
        first = raw_cache.fetch_row(row, False)
        second = raw_cache.fetch_row(row, False)
        expected = payload[row].tobytes()
        if first != expected or second != expected:
            raise AssertionError("raw bit-exact probe failed at row {}".format(row))
        digest.update(first)

    # A fresh group fill followed by all real group-member hits.
    group_cache = ReferenceMixedIOCache(geometry, payload, capacity_slots=3)
    group_rows = list(range(geometry.group_size))
    group_output = group_cache.fetch_rows(group_rows, [True] * len(group_rows))
    if group_output.tobytes() != payload[group_rows].tobytes():
        raise AssertionError("full-group bit-exact probe failed")
    digest.update(group_output.tobytes())

    # Exhaust every non-empty proper validity mask before a group request.
    partial_shapes = 0
    for valid_mask in range(1, geometry.full_valid_mask):
        partial = ReferenceMixedIOCache(geometry, payload, capacity_slots=3)
        partial.prime_slot(0, valid_mask)
        output = partial.fetch_row(0, True)
        if output != payload[0].tobytes():
            raise AssertionError(
                "partial-fill bit-exact probe failed for mask {}".format(valid_mask)
            )
        plan = geometry.plan_request(0, True, valid_mask)
        stats = partial.stats()
        if (
            stats["partial_fills"] != 1
            or stats["commands"] != len(plan.commands)
            or stats["physical_bytes"]
            != _popcount(plan.missing_mask) * geometry.subrow_bytes
            or not stats["reconciled"]
        ):
            raise AssertionError(
                "partial-fill counters failed for mask {}".format(valid_mask)
            )
        partial_shapes += 1
        digest.update(output)

    # One-slot FIFO eviction and reload.
    eviction = ReferenceMixedIOCache(geometry, payload, capacity_slots=1)
    rows = [0, geometry.rows_per_slot, 0]
    evicted_output = eviction.fetch_rows(rows, [False, False, False])
    if evicted_output.tobytes() != payload[rows].tobytes():
        raise AssertionError("eviction/reload bit-exact probe failed")
    if eviction.stats()["evictions"] != 2:
        raise AssertionError("eviction/reload probe did not perform two evictions")
    digest.update(evicted_output.tobytes())

    # Treat slot two as a replica of slot zero's real group rows.
    replica_payload = payload.copy()
    replica_start = 2 * geometry.rows_per_slot
    replica_payload[
        replica_start : replica_start + geometry.group_size
    ] = payload[: geometry.group_size]
    replica = ReferenceMixedIOCache(geometry, replica_payload, capacity_slots=1)
    replica_rows = [replica_start + offset for offset in range(geometry.group_size)]
    replica_output = replica.fetch_rows(replica_rows, [True] * geometry.group_size)
    if replica_output.tobytes() != payload[: geometry.group_size].tobytes():
        raise AssertionError("replica-row bit-exact probe failed")
    digest.update(replica_output.tobytes())

    return {
        "geometry_sha256": geometry.semantic_sha256(),
        "feature_row_bytes": geometry.feature_row_bytes,
        "group_size": geometry.group_size,
        "cache_slot_bytes": geometry.cache_slot_bytes,
        "subrow_count": geometry.subrow_count,
        "padding_rows": geometry.padding_rows,
        "partial_shapes": partial_shapes,
        "raw_subrow_positions": len(raw_rows),
        "bit_exact_sha256": digest.hexdigest(),
        "full_group_stats": group_cache.stats(),
        "eviction_stats": eviction.stats(),
        "status": "passed",
    }
